apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
  name: <apiserversource>
  namespace: "$namespace"
spec:
  serviceAccountName: <service-account>
  mode: Resource
  resources:
    - apiVersion: v1
      kind: Event
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: <sink>